### ISSUE TITLE
Support for EC_SECP224K1 curve

### ISSUE THREAD

**Issue by deadshot2491** [VirgilSecurity/VirgilCryptoiOS#23]
Hi, Is it possible to add EC_SECP224K1 curve type? The C++ library has the support for this variant and I'm trying to add this curve in your wrapper. I am new to Cryptography and working with C++. I am struggling a lot in adding the support for this type of curve(EC_SECP224K1) in iOS. Your help/guidance will be much appreciated, Thanks.

**Comment by Scratch-net** [comment]
Why do you need such a curve?

**Comment by deadshot2491** [comment]
Our backend uses this algorithm to do handshake with the existing Android applcation. We are developing iOS app for the same now. So I am trying to implement this curve in iOS.

**Comment by Scratch-net** [comment]
@deadshot2491 are you also using Virgil SDK on android and backend? I don't recall having some kind of "backend-android" handshake in our products

**Comment by deadshot2491** [comment]
No @Scratch-net , there were no library/ framework was available other than yours, which had EC algorithms for iOS. We are trying this on iOS alone.

**Comment by Scratch-net** [comment]
Can't help you, sorry. You can fork and modify the library on your own

**Comment by unlim-it** [comment]
Hey @deadshot2491, you can find this curve in our previous version of the library. Check it out https://github.com/VirgilSecurity/virgil-crypto-x/tree/v2

We don't have plans, for now, to support it in the new one.

**Comment by deadshot2491** [comment]
Okay Thanks, I'll try it out

**Comment by deadshot2491** [comment]
Hi @unlim-it , @Scratch-net  is there a way to generate shared secret between a public and private key using the swift wrapper?

**Comment by unlim-it** [comment]
Hey @deadshot2491, unfortunately, we don't have it in our iOS crypto wrapper. But you can find it in our source c++ crypto library here: 

https://github.com/VirgilSecurity/virgil-crypto/blob/ac65cfd4c0f26024b7f2eaa1e04fa6cf54ff9d54/lib/include/virgil/crypto/foundation/VirgilAsymmetricCipher.h#L224

Btw, can you share the details about your high-level use case that you are working on? Maybe we can help you make it easy?

**Comment by deadshot2491** [comment]
Thanks for the info @unlim-it , I modified the existing wrapper and added a method for generating the shared secret. Its working as expected!
